export const CREATE_TRAVEL_REQUEST = "CREATE_TRAVEL_REQUEST";
export const CREATE_TRAVEL_SUCCESS = "CREATE_TRAVEL_SUCCESS";
export const CREATE_TRAVEL_RESET = "CREATE_TRAVEL_RESET";
export const CREATE_TRAVEL_ERROR = "CREATE_TRAVEL_ERROR";
export const CREATE_TRAVEL_CLEAR_ERROR = "CREATE_TRAVEL_CLEAR_ERROR";

export const GET_TRAVELS_REQUEST = "GET_TRAVELS_REQUEST";
export const GET_TRAVELS_SUCCESS = "GET_TRAVELS_SUCCESS";
export const GET_TRAVELS_RESET = "GET_TRAVELS_RESET";
export const GET_TRAVELS_ERROR = "GET_TRAVELS_ERROR";
export const GET_TRAVELS_CLEAR_ERROR = "GET_TRAVELS_CLEAR_ERROR";

export const UPDATE_TRAVEL_REQUEST = "UPDATE_TRAVEL_REQUEST";
export const UPDATE_TRAVEL_SUCCESS = "UPDATE_TRAVEL_SUCCESS";
export const UPDATE_TRAVEL_RESET = "UPDATE_TRAVEL_RESET";
export const UPDATE_TRAVEL_ERROR = "UPDATE_TRAVEL_ERROR";
export const UPDATE_TRAVEL_CLEAR_ERROR = "UPDATE_TRAVEL_CLEAR_ERROR";

export const DELETE_TRAVEL_REQUEST = "DELETE_TRAVEL_REQUEST";
export const DELETE_TRAVEL_SUCCESS = "DELETE_TRAVEL_SUCCESS";
export const DELETE_TRAVEL_RESET = "DELETE_TRAVEL_RESET";
export const DELETE_TRAVEL_ERROR = "DELETE_TRAVEL_ERROR";
export const DELETE_TRAVEL_CLEAR_ERROR = "DELETE_TRAVEL_CLEAR_ERROR";
